# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from newteam import Ui_Dialog
tname=""
i=0
tvalue=1000
uvalue=0
batcount=0
bwlcount=0
arcount=0
wkcount=0
mycric=sqlite3.connect('cricket.db')
class Ui_MainWindow(object):
    def bat(self):
        if self.batradio.isChecked()==True:
            self.playerslist.clear()
            mycric=sqlite3.connect('cricket.db')
            curmycric=mycric.cursor()
            curmycric.execute("select player from stats where ctg='BAT'")
            while True:
                a=curmycric.fetchone()
                if a==None:
                    break
                else:
                    for b in a:
                        self.playerslist.addItem(str(b))
            mycric.close()
    def bowl(self):
        if self.bwlradio.isChecked()==True:
            self.playerslist.clear()
            mycric=sqlite3.connect('cricket.db')
            curmycric=mycric.cursor()
            curmycric.execute("select player from stats where ctg='BWL'")
            while True:
                a=curmycric.fetchone()
                if a==None:
                    break
                else:
                    for b in a:
                        self.playerslist.addItem(str(b))
            mycric.close()
    def ar(self):
        if self.arradio.isChecked()==True:
            self.playerslist.clear()
            mycric=sqlite3.connect('cricket.db')
            curmycric=mycric.cursor()
            curmycric.execute("select player from stats where ctg='AR'")
            while True:
                a=curmycric.fetchone()
                if a==None:
                    break
                else:
                    for b in a:
                        self.playerslist.addItem(str(b))
            mycric.close()
    def wk(self):
        if self.wkradio.isChecked()==True:
            self.playerslist.clear()
            mycric=sqlite3.connect('cricket.db')
            curmycric=mycric.cursor()
            curmycric.execute("select player from stats where ctg='WK'")
            while True:
                a=curmycric.fetchone()
                if a==None:
                    break
                else:
                    for b in a:
                        self.playerslist.addItem(str(b))
            mycric.close()
    
    
    def team(self, chose):
        txt=chose.text()
        if txt=="NEW Team":
            global i
            global tname
            tname="team"+str(i)
            self.teamlabel.setText(tname)
            i=i+1
        if txt=="SAVE Team":
            mycric.commit() 
        #if txt=="SAVE Team":
                        

    def addplayers(self, item):
        
        self.selectedplayerslist.addItem(QtWidgets.QListWidgetItem(item))
        n=self.playerslist.row(item)
        t=self.playerslist.takeItem(n).text()
        global tname
        curmycric=mycric.cursor()
        curmycric.execute("select value from stats where player=?",(t,))
        a=curmycric.fetchone()
        for b in a:
            v=int(b)
        curmycric.execute("INSERT INTO teams(name,players,value)VALUES(?,?,?)",(tname,t,v,))
        global tvalue
        global uvalue
        tvalue=tvalue-v
        uvalue=uvalue+v
        self.ptsavllabel.setText(str(tvalue))
        self.ptsusedlabel.setText(str(uvalue))
        curmycric.execute("select ctg from stats where player=?",(t,))
        c=curmycric.fetchone()
        global batcount
        global bwlcount
        global arcount
        global wkcount
        for s in c:
            c1=s
        if c1=="BAT":
            batcount=batcount+1
            self.batcountlabel.setText(str(batcount))
        if c1=="BWL":
            bwlcount=bwlcount+1
            self.bwlcountlabel.setText(str(bwlcount))
        if c1=="AR":
            arcount=arcount+1
            self.arcountlabel.setText(str(arcount))
        if c1=="WK":
            wkcount=wkcount+1
            self.wkcountlabel.setText(str(wkcount))
        
            



        
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.playerslist = QtWidgets.QListWidget(self.centralwidget)
        self.playerslist.setGeometry(QtCore.QRect(40, 230, 301, 301))
        self.playerslist.setObjectName("playerslist")
        self.selectedplayerslist = QtWidgets.QListWidget(self.centralwidget)
        self.selectedplayerslist.setGeometry(QtCore.QRect(380, 230, 301, 301))
        self.selectedplayerslist.setObjectName("selectedplayerslist")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 180, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.batradio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.batradio.setObjectName("batradio")
        self.horizontalLayout.addWidget(self.batradio)
        self.bwlradio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.bwlradio.setObjectName("bwlradio")
        self.horizontalLayout.addWidget(self.bwlradio)
        self.arradio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.arradio.setObjectName("arradio")
        self.horizontalLayout.addWidget(self.arradio)
        self.wkradio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.wkradio.setObjectName("wkradio")
        self.horizontalLayout.addWidget(self.wkradio)
        self.batradio.toggled.connect(self.bat)
        self.bwlradio.toggled.connect(self.bowl)
        self.arradio.toggled.connect(self.ar)
        self.wkradio.toggled.connect(self.wk)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 654, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.batcountlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.batcountlabel.setObjectName("batcountlabel")
        self.horizontalLayout_2.addWidget(self.batcountlabel)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.bwlcountlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bwlcountlabel.setObjectName("bwlcountlabel")
        self.horizontalLayout_2.addWidget(self.bwlcountlabel)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.arcountlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.arcountlabel.setObjectName("arcountlabel")
        self.horizontalLayout_2.addWidget(self.arcountlabel)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.wkcountlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wkcountlabel.setObjectName("wkcountlabel")
        self.horizontalLayout_2.addWidget(self.wkcountlabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 310, 31, 21))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 120, 301, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ptsl1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.ptsl1.setObjectName("ptsl1")
        self.horizontalLayout_3.addWidget(self.ptsl1)
        self.ptsavllabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.ptsavllabel.setObjectName("ptsavllabel")
        self.horizontalLayout_3.addWidget(self.ptsavllabel)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(380, 120, 301, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ptsl2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.ptsl2.setObjectName("ptsl2")
        self.horizontalLayout_4.addWidget(self.ptsl2)
        self.ptsusedlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.ptsusedlabel.setObjectName("ptsusedlabel")
        self.horizontalLayout_4.addWidget(self.ptsusedlabel)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(380, 180, 301, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.teamlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.teamlabel.setObjectName("teamlabel")
        self.horizontalLayout_5.addWidget(self.teamlabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 22))
        self.menubar.setObjectName("menubar")
        self.menuMANAGE_TEAMS = QtWidgets.QMenu(self.menubar)
        self.menuMANAGE_TEAMS.setObjectName("menuMANAGE_TEAMS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setCheckable(False)
        self.actionNEW_Team.setChecked(False)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionSAVE_Team = QtWidgets.QAction(MainWindow)
        self.actionSAVE_Team.setObjectName("actionSAVE_Team")
        self.actionMANAGE_Team = QtWidgets.QAction(MainWindow)
        self.actionMANAGE_Team.setObjectName("actionMANAGE_Team")
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        self.menuMANAGE_TEAMS.addAction(self.actionNEW_Team)
        self.menuMANAGE_TEAMS.addAction(self.actionSAVE_Team)
        self.menuMANAGE_TEAMS.addAction(self.actionMANAGE_Team)
        self.menuMANAGE_TEAMS.addSeparator()
        self.menuMANAGE_TEAMS.addAction(self.actionEVALUATE_Team)
        self.menubar.addAction(self.menuMANAGE_TEAMS.menuAction())

        self.retranslateUi(MainWindow)
        self.playerslist.setCurrentRow(-1)
        self.playerslist.itemDoubleClicked['QListWidgetItem*'].connect(self.addplayers)
        self.menubar.triggered[QtWidgets.QAction].connect(self.team)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.batradio.setText(_translate("MainWindow", "BAT"))
        self.bwlradio.setText(_translate("MainWindow", "BWL"))
        self.arradio.setText(_translate("MainWindow", "AR"))
        self.wkradio.setText(_translate("MainWindow", "WK"))
        self.label.setText(_translate("MainWindow", "YOUR SELECTIONS"))
        self.label_3.setText(_translate("MainWindow", "Batsman[BAT}"))
        self.batcountlabel.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Bowler[BWL]"))
        self.bwlcountlabel.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Allrouders[AR]"))
        self.arcountlabel.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Wicket-keeper"))
        self.wkcountlabel.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", ">"))
        self.ptsl1.setText(_translate("MainWindow", "Points Available"))
        self.ptsavllabel.setText(_translate("MainWindow", "1000"))
        self.ptsl2.setText(_translate("MainWindow", "Points Used"))
        self.ptsusedlabel.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Team Name"))
        self.teamlabel.setText(_translate("MainWindow", "Click  NEW team"))
        self.menuMANAGE_TEAMS.setTitle(_translate("MainWindow", "MANAGE TEAMS"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionSAVE_Team.setText(_translate("MainWindow", "SAVE Team"))
        self.actionMANAGE_Team.setText(_translate("MainWindow", "MANAGE Team"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
